---
- name: Generate password and save
  hosts: all
  gather_facts: false
  connection: local
  serial: 1

  vars_files:
    - ../../inventory/common/vault-common-vars.yml

  tasks:
    - name: save the hostname as a variable
      set_fact:
        key: "{{ inventory_hostname }}"

    - name: vault password
      block:
        - file: dest=/var/local/hsmenc mode=0400
        
        - shell: sudo /usr/local/bin/cxitool Dev={{ hsmservers[0].host }} logonpass={{ hsm_user }},{{ hsm_passwd }} name=AES_{{ hsm_user }} infile=/var/local/hsmenc outfile=/dev/shm/hsmenc.tmp decrypt=ECB,PKCS5

        - lineinfile: dest=/dev/shm/hsmenc.tmp line="{{ key }} {{ password }}" backup=no create=yes mode=0400

        - shell: sudo /usr/local/bin/cxitool Dev={{ hsmservers[0].host }} logonpass={{ hsm_user }},{{ hsm_passwd }} name=AES_{{ hsm_user }} infile=/dev/shm/hsmenc.tmp outfile=/var/local/hsmenc encrypt=ECB,PKCS5

        - file: dest=/dev/shm/hsmenc.tmp state=absent
      delegate_to: localhost
      become: true
      no_log: true
      when: (userdata.LD_LOC == 'phx' or userdata.LD_LOC == 'snv') and createinfo is defined

    - name: output password
      debug: msg="{{ key }} {{ password }}"
      when: (userdata.LD_LOC == 'phx' or userdata.LD_LOC == 'snv') and createinfo is defined

    - name: set user and password
      block:
        - set_fact: ansible_user=root

        - set_fact: ansible_ssh_pass={{ password }}
      when: userdata.LD_LOC == 'phx' or userdata.LD_LOC == 'snv'
